// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToyBoxApi.Data;

#nullable disable

namespace ToyBoxApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260928100955_AddChildren")]
    partial class AddChildren
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToyBoxApi.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category_name");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Educational"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Creative"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Vehicles"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Dolls & Figures"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Outdoor & Sports"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Puzzles & Games"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Building Blocks"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Electronic Toys"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Stuffed Animals"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Arts & Crafts"
                        });
                });

            modelBuilder.Entity("ToyBoxApi.Entities.Child", b =>
                {
                    b.Property<int>("ChildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("child_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChildId"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Interests")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("interests");

                    b.Property<bool>("IsVisibleToContacts")
                        .HasColumnType("bit")
                        .HasColumnName("is_visible_to_contacts");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("ParentUserId")
                        .HasColumnType("int")
                        .HasColumnName("parent_user_id");

                    b.HasKey("ChildId");

                    b.HasIndex("ParentUserId");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.Contact", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("ContactId")
                        .HasColumnType("int")
                        .HasColumnName("contact_id");

                    b.HasKey("UserId", "ContactId");

                    b.HasIndex("ContactId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.ExchangeRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DueSoonNotifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("due_soon_notified_at");

                    b.Property<string>("ExchangeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("exchange_type");

                    b.Property<int>("InitiatorUserId")
                        .HasColumnType("int")
                        .HasColumnName("initiator_user_id");

                    b.Property<DateTime?>("LoanStartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("loan_started_at");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("message");

                    b.Property<DateTime?>("OverdueNotifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("overdue_notified_at");

                    b.Property<int?>("ReceiverUserId")
                        .HasColumnType("int")
                        .HasColumnName("receiver_user_id");

                    b.Property<bool>("ReturnConfirmedByInitiator")
                        .HasColumnType("bit")
                        .HasColumnName("return_confirmed_by_initiator");

                    b.Property<bool>("ReturnConfirmedByReceiver")
                        .HasColumnType("bit")
                        .HasColumnName("return_confirmed_by_receiver");

                    b.Property<DateTime?>("ReturnDueAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("return_due_at");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("returned_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("RequestId");

                    b.HasIndex("InitiatorUserId");

                    b.HasIndex("ReceiverUserId");

                    b.ToTable("Exchange_Requests");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.ExchangeRequestToy", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.Property<int>("ToyId")
                        .HasColumnType("int")
                        .HasColumnName("toy_id");

                    b.Property<string>("ExchangeRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("exchange_role");

                    b.Property<decimal?>("ValueAtRequest")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("value_at_request");

                    b.HasKey("RequestId", "ToyId");

                    b.HasIndex("ToyId");

                    b.ToTable("Exchange_Request_Toys");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("int")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("Body")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("GiftId")
                        .HasColumnType("int")
                        .HasColumnName("gift_id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("title");

                    b.Property<int?>("ToyId")
                        .HasColumnType("int")
                        .HasColumnName("toy_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId", "IsRead", "CreatedAt");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("review_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("RatingScore")
                        .HasColumnType("int")
                        .HasColumnName("rating_score");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.Property<int>("RevieweeUserId")
                        .HasColumnType("int")
                        .HasColumnName("reviewee_user_id");

                    b.Property<int>("ReviewerUserId")
                        .HasColumnType("int")
                        .HasColumnName("reviewer_user_id");

                    b.HasKey("ReviewId");

                    b.HasIndex("RevieweeUserId");

                    b.HasIndex("ReviewerUserId");

                    b.HasIndex("RequestId", "ReviewerUserId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.SharedToy", b =>
                {
                    b.Property<int>("SharedWithUserId")
                        .HasColumnType("int")
                        .HasColumnName("shared_with_user_id");

                    b.Property<int>("ToyId")
                        .HasColumnType("int")
                        .HasColumnName("toy_id");

                    b.HasKey("SharedWithUserId", "ToyId");

                    b.HasIndex("ToyId");

                    b.ToTable("Shared_Toys");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.Toy", b =>
                {
                    b.Property<int>("ToyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("toy_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToyId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<int?>("ConditionStatus")
                        .HasColumnType("int")
                        .HasColumnName("condition_status");

                    b.Property<int>("CurrentHolderUserId")
                        .HasColumnType("int")
                        .HasColumnName("current_holder_user_id");

                    b.Property<int?>("DesiredCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("desired_category_id");

                    b.Property<bool>("IsListed")
                        .HasColumnType("bit")
                        .HasColumnName("is_listed");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("int")
                        .HasColumnName("owner_user_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<string>("ToyDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("toy_description");

                    b.Property<string>("ToyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("toy_name");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("value");

                    b.HasKey("ToyId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CurrentHolderUserId");

                    b.HasIndex("DesiredCategoryId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Toys");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.ToyGift", b =>
                {
                    b.Property<int>("GiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("gift_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GiftId"));

                    b.Property<int?>("ChildId")
                        .HasColumnType("int")
                        .HasColumnName("child_id");

                    b.Property<string>("ChildName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("child_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("FromUserId")
                        .HasColumnType("int")
                        .HasColumnName("from_user_id");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("message");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("responded_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int>("ToUserId")
                        .HasColumnType("int")
                        .HasColumnName("to_user_id");

                    b.Property<int>("ToyId")
                        .HasColumnType("int")
                        .HasColumnName("toy_id");

                    b.HasKey("GiftId");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToyId");

                    b.HasIndex("ToUserId", "Status");

                    b.ToTable("Toy_Gifts");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.ToyImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("image_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_url");

                    b.Property<int>("ToyId")
                        .HasColumnType("int")
                        .HasColumnName("toy_id");

                    b.HasKey("ImageId");

                    b.HasIndex("ToyId");

                    b.ToTable("Toy_Images");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.ToyOwnershipHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("history_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ended_at");

                    b.Property<int?>("GiftId")
                        .HasColumnType("int")
                        .HasColumnName("gift_id");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at");

                    b.Property<int>("ToyId")
                        .HasColumnType("int")
                        .HasColumnName("toy_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("HistoryId");

                    b.HasIndex("UserId");

                    b.HasIndex("ToyId", "EndedAt");

                    b.ToTable("Toy_Ownership_History");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.ToyPriority", b =>
                {
                    b.Property<int>("ToyId")
                        .HasColumnType("int")
                        .HasColumnName("toy_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.HasKey("ToyId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Toy_Priorities");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_no");

                    b.Property<string>("ProfilePic")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("profile_pic");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("rating");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.Child", b =>
                {
                    b.HasOne("ToyBoxApi.Entities.User", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.Contact", b =>
                {
                    b.HasOne("ToyBoxApi.Entities.User", "ContactUser")
                        .WithMany("ContactsAsContact")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ToyBoxApi.Entities.User", "User")
                        .WithMany("ContactsAsUser")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContactUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.ExchangeRequest", b =>
                {
                    b.HasOne("ToyBoxApi.Entities.User", "Initiator")
                        .WithMany("InitiatedRequests")
                        .HasForeignKey("InitiatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ToyBoxApi.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Initiator");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.ExchangeRequestToy", b =>
                {
                    b.HasOne("ToyBoxApi.Entities.ExchangeRequest", "ExchangeRequest")
                        .WithMany("Toys")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToyBoxApi.Entities.Toy", "Toy")
                        .WithMany("ExchangeRequestToys")
                        .HasForeignKey("ToyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExchangeRequest");

                    b.Navigation("Toy");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.Notification", b =>
                {
                    b.HasOne("ToyBoxApi.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.Review", b =>
                {
                    b.HasOne("ToyBoxApi.Entities.ExchangeRequest", "ExchangeRequest")
                        .WithMany("Reviews")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToyBoxApi.Entities.User", "Reviewee")
                        .WithMany("ReviewsReceived")
                        .HasForeignKey("RevieweeUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ToyBoxApi.Entities.User", "Reviewer")
                        .WithMany("ReviewsGiven")
                        .HasForeignKey("ReviewerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExchangeRequest");

                    b.Navigation("Reviewee");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.SharedToy", b =>
                {
                    b.HasOne("ToyBoxApi.Entities.User", "SharedWithUser")
                        .WithMany("SharedToys")
                        .HasForeignKey("SharedWithUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ToyBoxApi.Entities.Toy", "Toy")
                        .WithMany("SharedWith")
                        .HasForeignKey("ToyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SharedWithUser");

                    b.Navigation("Toy");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.Toy", b =>
                {
                    b.HasOne("ToyBoxApi.Entities.Category", "Category")
                        .WithMany("ToysInCategory")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ToyBoxApi.Entities.User", "CurrentHolder")
                        .WithMany()
                        .HasForeignKey("CurrentHolderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ToyBoxApi.Entities.Category", "DesiredCategory")
                        .WithMany("ToysDesiredCategory")
                        .HasForeignKey("DesiredCategoryId");

                    b.HasOne("ToyBoxApi.Entities.User", "Owner")
                        .WithMany("Toys")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CurrentHolder");

                    b.Navigation("DesiredCategory");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.ToyGift", b =>
                {
                    b.HasOne("ToyBoxApi.Entities.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ToyBoxApi.Entities.User", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ToyBoxApi.Entities.Toy", "Toy")
                        .WithMany("Gifts")
                        .HasForeignKey("ToyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");

                    b.Navigation("Toy");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.ToyImage", b =>
                {
                    b.HasOne("ToyBoxApi.Entities.Toy", "Toy")
                        .WithMany("Images")
                        .HasForeignKey("ToyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Toy");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.ToyOwnershipHistory", b =>
                {
                    b.HasOne("ToyBoxApi.Entities.Toy", "Toy")
                        .WithMany("History")
                        .HasForeignKey("ToyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToyBoxApi.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Toy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.ToyPriority", b =>
                {
                    b.HasOne("ToyBoxApi.Entities.Toy", "Toy")
                        .WithMany("Priorities")
                        .HasForeignKey("ToyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToyBoxApi.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Toy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.Category", b =>
                {
                    b.Navigation("ToysDesiredCategory");

                    b.Navigation("ToysInCategory");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.ExchangeRequest", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("Toys");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.Toy", b =>
                {
                    b.Navigation("ExchangeRequestToys");

                    b.Navigation("Gifts");

                    b.Navigation("History");

                    b.Navigation("Images");

                    b.Navigation("Priorities");

                    b.Navigation("SharedWith");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.User", b =>
                {
                    b.Navigation("ContactsAsContact");

                    b.Navigation("ContactsAsUser");

                    b.Navigation("InitiatedRequests");

                    b.Navigation("ReviewsGiven");

                    b.Navigation("ReviewsReceived");

                    b.Navigation("SharedToys");

                    b.Navigation("Toys");
                });
#pragma warning restore 612, 618
        }
    }
}
