// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToyBoxApi.Data;

#nullable disable

namespace ToyBoxApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260926083108_AddValueAtRequestToExchangeRequestToy")]
    partial class AddValueAtRequestToExchangeRequestToy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToyBoxApi.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category_name");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Educational"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Creative"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Vehicles"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Dolls & Figures"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Outdoor & Sports"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Puzzles & Games"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Building Blocks"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Electronic Toys"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Stuffed Animals"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Arts & Crafts"
                        });
                });

            modelBuilder.Entity("ToyBoxApi.Entities.Contact", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("ContactId")
                        .HasColumnType("int")
                        .HasColumnName("contact_id");

                    b.HasKey("UserId", "ContactId");

                    b.HasIndex("ContactId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.ExchangeRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("InitiatorUserId")
                        .HasColumnType("int")
                        .HasColumnName("initiator_user_id");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("message");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("RequestId");

                    b.HasIndex("InitiatorUserId");

                    b.ToTable("Exchange_Requests");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.ExchangeRequestToy", b =>
                {
                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.Property<int>("ToyId")
                        .HasColumnType("int")
                        .HasColumnName("toy_id");

                    b.Property<string>("ExchangeRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("exchange_role");

                    b.Property<decimal?>("ValueAtRequest")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("value_at_request");

                    b.HasKey("RequestId", "ToyId");

                    b.HasIndex("ToyId");

                    b.ToTable("Exchange_Request_Toys");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("review_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("RatingScore")
                        .HasColumnType("int")
                        .HasColumnName("rating_score");

                    b.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    b.Property<int>("RevieweeUserId")
                        .HasColumnType("int")
                        .HasColumnName("reviewee_user_id");

                    b.Property<int>("ReviewerUserId")
                        .HasColumnType("int")
                        .HasColumnName("reviewer_user_id");

                    b.HasKey("ReviewId");

                    b.HasIndex("RevieweeUserId");

                    b.HasIndex("ReviewerUserId");

                    b.HasIndex("RequestId", "ReviewerUserId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.SharedToy", b =>
                {
                    b.Property<int>("SharedWithUserId")
                        .HasColumnType("int")
                        .HasColumnName("shared_with_user_id");

                    b.Property<int>("ToyId")
                        .HasColumnType("int")
                        .HasColumnName("toy_id");

                    b.HasKey("SharedWithUserId", "ToyId");

                    b.HasIndex("ToyId");

                    b.ToTable("Shared_Toys");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.Toy", b =>
                {
                    b.Property<int>("ToyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("toy_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ToyId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<int?>("ConditionStatus")
                        .HasColumnType("int")
                        .HasColumnName("condition_status");

                    b.Property<int?>("DesiredCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("desired_category_id");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("int")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("ToyDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("toy_description");

                    b.Property<string>("ToyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("toy_name");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("value");

                    b.HasKey("ToyId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DesiredCategoryId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Toys");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.ToyImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("image_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("image_url");

                    b.Property<int>("ToyId")
                        .HasColumnType("int")
                        .HasColumnName("toy_id");

                    b.HasKey("ImageId");

                    b.HasIndex("ToyId");

                    b.ToTable("Toy_Images");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_no");

                    b.Property<string>("ProfilePic")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("profile_pic");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("rating");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.Contact", b =>
                {
                    b.HasOne("ToyBoxApi.Entities.User", "ContactUser")
                        .WithMany("ContactsAsContact")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ToyBoxApi.Entities.User", "User")
                        .WithMany("ContactsAsUser")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContactUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.ExchangeRequest", b =>
                {
                    b.HasOne("ToyBoxApi.Entities.User", "Initiator")
                        .WithMany("InitiatedRequests")
                        .HasForeignKey("InitiatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Initiator");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.ExchangeRequestToy", b =>
                {
                    b.HasOne("ToyBoxApi.Entities.ExchangeRequest", "ExchangeRequest")
                        .WithMany("Toys")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToyBoxApi.Entities.Toy", "Toy")
                        .WithMany("ExchangeRequestToys")
                        .HasForeignKey("ToyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExchangeRequest");

                    b.Navigation("Toy");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.Review", b =>
                {
                    b.HasOne("ToyBoxApi.Entities.ExchangeRequest", "ExchangeRequest")
                        .WithMany("Reviews")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToyBoxApi.Entities.User", "Reviewee")
                        .WithMany("ReviewsReceived")
                        .HasForeignKey("RevieweeUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ToyBoxApi.Entities.User", "Reviewer")
                        .WithMany("ReviewsGiven")
                        .HasForeignKey("ReviewerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExchangeRequest");

                    b.Navigation("Reviewee");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.SharedToy", b =>
                {
                    b.HasOne("ToyBoxApi.Entities.User", "SharedWithUser")
                        .WithMany("SharedToys")
                        .HasForeignKey("SharedWithUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ToyBoxApi.Entities.Toy", "Toy")
                        .WithMany("SharedWith")
                        .HasForeignKey("ToyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SharedWithUser");

                    b.Navigation("Toy");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.Toy", b =>
                {
                    b.HasOne("ToyBoxApi.Entities.Category", "Category")
                        .WithMany("ToysInCategory")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ToyBoxApi.Entities.Category", "DesiredCategory")
                        .WithMany("ToysDesiredCategory")
                        .HasForeignKey("DesiredCategoryId");

                    b.HasOne("ToyBoxApi.Entities.User", "Owner")
                        .WithMany("Toys")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("DesiredCategory");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.ToyImage", b =>
                {
                    b.HasOne("ToyBoxApi.Entities.Toy", "Toy")
                        .WithMany("Images")
                        .HasForeignKey("ToyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Toy");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.Category", b =>
                {
                    b.Navigation("ToysDesiredCategory");

                    b.Navigation("ToysInCategory");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.ExchangeRequest", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("Toys");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.Toy", b =>
                {
                    b.Navigation("ExchangeRequestToys");

                    b.Navigation("Images");

                    b.Navigation("SharedWith");
                });

            modelBuilder.Entity("ToyBoxApi.Entities.User", b =>
                {
                    b.Navigation("ContactsAsContact");

                    b.Navigation("ContactsAsUser");

                    b.Navigation("InitiatedRequests");

                    b.Navigation("ReviewsGiven");

                    b.Navigation("ReviewsReceived");

                    b.Navigation("SharedToys");

                    b.Navigation("Toys");
                });
#pragma warning restore 612, 618
        }
    }
}
